src/blog/urls.py
from django.conf.urls import url

from .views import PostList, PostDetail

urlpatterns = [
    url(r'^$', PostList.as_view(), name='post_list'),
    url(r'^(?P<slug>[a-z0-9\-]+)/$', PostDetail.as_view(), name='post_detail'),
]

src/frontend/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="frontend/index.html"), name='index'),
]

src/lessons/urls.py
from django.conf.urls import url

from .views import SeriesListView, SeriesDetailView, LessonDetailView

urlpatterns = [
    url(r'^$', SeriesListView.as_view(), name='series_list'),
    url(r'^(?P<slug>[a-z0-9\-]+)/$', SeriesDetailView.as_view(), name='series_detail'),
    url(r'^(?P<series_slug>[a-z0-9\-]+)/(?P<slug>[a-z0-9\-]+)/$', LessonDetailView.as_view(), name='detail'),
]

src/pykrd/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('frontend.urls', namespace='frontend')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^lessons/', include('lessons.urls', namespace='lessons')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Tag(models.Model):
    name = models.CharField(max_length=128, blank=False, null=False, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=128, blank=False, null=False)
    content = RichTextUploadingField()
    cover = models.ImageField(upload_to='post', default=None, null=True, blank=False)
    preview = RichTextField(default=None, null=True, blank=False)
    slug = models.SlugField(max_length=128)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

src/frontend/models.py
from django.db import models

# Create your models here.

src/lessons/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Series(models.Model):
    name = models.CharField(max_length=128, blank=False, null=False, unique=True)
    description = RichTextField(blank=True, null=True, default=None)
    cover = models.ImageField(upload_to='series')
    slug = models.SlugField(max_length=128, blank=False, null=False, default='')
    position = models.IntegerField(blank=False, null=False, default=0)

    def __str__(self):
        return self.name


class Lesson(models.Model):
    title = models.CharField(max_length=128, blank=False, null=False)
    preview = RichTextField(blank=False, null=False, default=None)
    content = RichTextUploadingField(blank=False, null=False)
    series = models.ForeignKey(Series)
    position = models.IntegerField(default=0)
    slug = models.SlugField(blank=False, null=False, default='')

    def __str__(self):
        return self.title

src/blog/views.py
from django.views.generic import ListView, DetailView

from .models import Post, Tag


class PostList(ListView):
    model = Post
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()[:15]
        return context


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()[:15]
        return context

src/frontend/views.py
from django.shortcuts import render

src/lessons/views.py
from django.views.generic import ListView, DetailView

from .models import Series, Lesson


class SeriesListView(ListView):
    model = Series


class SeriesDetailView(DetailView):
    model = Series


class LessonDetailView(DetailView):
    model = Lesson

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <link rel="shortcut icon" href="{% static 'img/icon.ico' %}" />
    <link rel="icon" type="image/png" href="{% static 'img/icon.png' %}" />

    {% block head_tag %}

        <!--Import Google Icon Font-->
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'materialize/dist/css/materialize.css' %}"
              media="screen,projection"/>
        <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    {% endblock %}

</head>

<body>

    <nav class="blue darken-2" role="navigation">
        <div class="nav-wrapper container">
            <a id="logo-container" href="{% url 'frontend:index' %}" class="brand-logo">
                <img src="{% static 'img/logo.png' %}" height="24"> PyKrasnodar
            </a>
            <ul class="right hide-on-med-and-down">
                <li {% if request.path|slice:':2' == '/' %}class="active"{% endif %}>
                    <a href="{% url 'frontend:index' %}">Главная</a>
                </li>
                <li {% if request.path|slice:':6' == '/blog/' %}class="active"{% endif %}>
                    <a href="{% url 'blog:post_list' %}">Блог</a>
                </li>
                <li {% if request.path|slice:':9' == '/lessons/' %}class="active"{% endif %}>
                    <a href="{% url 'lessons:series_list' %}">Уроки</a>
                </li>
            </ul>

            <ul id="nav-mobile" class="side-nav">
                <li {% if request.path|slice:':2' == '/' %}class="active"{% endif %}><a href="{% url 'frontend:index' %}">Главная</a></li>
                <li {% if request.path|slice:':6' == '/blog/' %}class="active"{% endif %}><a href="{% url 'blog:post_list' %}">Блог</a></li>
                <li {% if request.path|slice:':9' == '/lessons/' %}class="active"{% endif %}><a href="{% url 'lessons:series_list' %}">Уроки</a></li>
            </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
    </nav>

    {% block content %}{% endblock %}

    <footer class="page-footer orange">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">Python Krasnodar</h5>
                    <p class="grey-text text-lighten-4">
                        Группа краснодарских Python-разработчиков. Вся информация о Python для Краснодарского community.
                    </p>

                    <p>
                        <a class="black-text" href="https://github.com/python-krasnodar"><i class="fa fa-github"></i> GitHub</a><br>
                        <a class="blue-text text-darken-4" href="https://new.vk.com/python_krasnodar"><i class="fa fa-vk"></i> VKontakte</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
            </div>
        </div>
    </footer>

    {% block body_tag_end %}

        <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="{% static 'jquery/dist/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'materialize/dist/js/materialize.min.js' %}"></script>
        <script>
            (function ($) {
                $(function () {

                    $('.button-collapse').sideNav();

                    if ($('.tags-pushpin-content').length) {
                        $('.tags-pushpin-content').pushpin({top: $('.tags-pushpin-wrapper').offset().top});
                    }

                    $('.carousel.carousel-slider').carousel({full_width: true});
                });
            })(jQuery);
        </script>

    {% endblock %}

</body>
</html>

src/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m8">
                <div class="card">
                    <div class="card-image">
                        <img src="{{ object.cover.url }}">
                    </div>
                    <div class="card-content">
                        <span class="card-title">{{ object.title }}</span>
                        {{ object.content|safe }}
                    </div>
                    <div class="card-action">
                            {% for tag in post.tags.all %}
                                <a class="blue-text" href="#">#{{ tag }}</a>
                            {% endfor %}
                    </div>
                </div>
            </div>

            <!-- tags -->
            <div class="col s12 m4">
                <div class="tags-pushpin-wrapper">
                    <div class="tags-pushpin-content">
                        <div class="card">
                            <div class="card-content">
                                <span class="card-title">Тэги</span>
                                <p>
                                    {% for tag in tags %}
                                        <a href="#">#{{ tag }}</a>
                                    {% endfor %}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2>Последние посты</h2>
        <div class="row">
            <div class="col s12 m8">
                {% for post in object_list %}

                    <div class="card large">
                        <div class="card-image">
                            <img src="{{ post.cover.url }}">
                        </div>
                        <div class="card-content">
                            <a href="{% url 'blog:post_detail' post.slug %}" class="card-title">{{ post.title }}</a>
                            {{ post.preview|safe }}
                        </div>
                        <div class="card-action">
                            {% for tag in post.tags.all %}
                                <a class="blue-text" href="#">#{{ tag }}</a>
                            {% endfor %}
                        </div>
                    </div>
                {% empty %}
                    <div class="card">
                        <div class="card-content">
                            <p>Еще нет постов</p>
                        </div>
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    {% if page_obj.has_previous %}
                        <a class="btn blue darken-2 left" href="{% url 'blog:post_list' %}?page={{ page_obj.previous_page_number }}">Назад</a>
                    {% endif %}

                    {% if page_obj.has_next %}
                        <a class="btn blue darken-2 right" href="{% url 'blog:post_list' %}?page={{ page_obj.next_page_number }}">Вперед</a>
                    {% endif %}
                {% endif %}
            </div>

            <!-- tags -->
            <div class="col s12 m4">
                <div class="tags-pushpin-wrapper">
                    <div class="tags-pushpin-content">
                        <div class="card">
                            <div class="card-content">
                                <span class="card-title">Тэги</span>
                                <p>
                                    {% for tag in tags %}
                                        <a href="#">#{{ tag }}</a>
                                    {% endfor %}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/frontend/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="video-container">
        <iframe width="1280" height="720" src="https://www.youtube-nocookie.com/embed/SdH8fI1aNZA?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
    </div>

    <div class="container">
        <div class="section">

            <!--   Icon Section   -->
            <div class="row">
                <div class="col s12 m4">
                    <div class="icon-block">
                        <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
                        <h5 class="center">Speeds up development</h5>

                        <p class="light">We did most of the heavy lifting for you to provide a default stylings that
                            incorporate our custom components. Additionally, we refined animations and transitions to
                            provide a smoother experience for developers.</p>
                    </div>
                </div>

                <div class="col s12 m4">
                    <div class="icon-block">
                        <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
                        <h5 class="center">User Experience Focused</h5>

                        <p class="light">By utilizing elements and principles of Material Design, we were able to create
                            a
                            framework that incorporates components and animations that provide more feedback to users.
                            Additionally, a single underlying responsive system across all platforms allow for a more
                            unified user experience.</p>
                    </div>
                </div>

                <div class="col s12 m4">
                    <div class="icon-block">
                        <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
                        <h5 class="center">Easy to work with</h5>

                        <p class="light">We have provided detailed documentation as well as specific code examples to
                            help
                            new users get started. We are also always open to feedback and can answer any questions a
                            user
                            may have about Materialize.</p>
                    </div>
                </div>
            </div>

        </div>
        <br><br>

        <div class="section">

        </div>
    </div>

{% endblock %}

src/templates/lessons/lesson_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ object.title }}</span>
                        {{ object.content|safe }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/lessons/series_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m6">
                <div class="card">
                    <div class="card-image">
                        <img src="{{ object.cover.url }}">
                    </div>
                </div>
            </div>
            <div class="col s12 m6">
                <div class="card">
                    <div class="card-content">
                        <h4 class="card-title">{{ object.name }}</h4>
                        {{ object.description|safe }}
                    </div>
                </div>
            </div>
        </div>

        {% for lesson in object.lesson_set.all %}
            <div class="row">
                <div class="col s12">
                    <div class="card">
                        <div class="card-content">
                            <a href="{% url 'lessons:detail' object.slug lesson.slug %}" class="card-title">{{ lesson.title }}</a>
                            {{ lesson.preview|safe }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/templates/lessons/series_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col s12 m6">
                {% for series in object_list %}
                    {% if not forloop.counter|divisibleby:2 %}
                        <div class="card large">
                            <div class="card-image">
                                <img src="{{ series.cover.url }}">
                            </div>
                            <div class="card-content">
                                <a href="{% url 'lessons:series_detail' series.slug %}"
                                   class="card-title">{{ series.name }}</a>
                                {{ series.description|safe }}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="col s12 m6">
                {% for series in object_list %}
                    {% if forloop.counter|divisibleby:2 %}
                        <div class="card large">
                            <div class="card-image">
                                <img src="{{ series.cover.url }}">
                            </div>
                            <div class="card-content">
                                <a href="{% url 'lessons:series_detail' series.slug %}"
                                   class="card-title">{{ series.name }}</a>
                                {{ series.description|safe }}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/lessons/lesson_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <section>{{ object.content }}</section>
{% endblock %}

templates/lessons/series_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <section>{{ object.description }}</section>

    <h2>Список уроков</h2>
    <ul>
        {% for lesson in series.lesson_set.all %}
            <li>
                <a href="{% url 'lessons:detail' series.slug lesson.slug %}">{{ lesson.title }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}